// ------------------------------------------------------------------------------
// <autogenerated>
// This code was generated by a tool.
// Runtime Version: 1.0.3705.288
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------------


using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;
using Microsoft.VisualBasic.CompilerServices;

// 
// このソース コードは Microsoft.VSDesigner、バージョン 1.0.3705.288 によって自動生成されました。
// 
namespace Densan.Reams.AB.AB000BB.localhost
{

    // <remarks/>
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "AACommonBSClassSoap", Namespace = "http://Reams.ndensan.co.jp")]
    public class AACommonBSClass : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        // <remarks/>
        public AACommonBSClass() : base()
        {
            this.Url = "http://localhost/Densan/Reams/AA/AA001BS/AACommonBSClass.asmx";
        }

        // <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/JukiRendoInterface", RequestNamespace = "http://Reams.ndensan.co.jp", ResponseNamespace = "http://Reams.ndensan.co.jp", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void JukiRendoInterface(AAJUKIRENDOParamClass cAAJUKIRENDOParam)
        {
            this.Invoke("JukiRendoInterface", new object[] { cAAJUKIRENDOParam });
        }

        // <remarks/>
        public IAsyncResult BeginJukiRendoInterface(AAJUKIRENDOParamClass cAAJUKIRENDOParam, AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("JukiRendoInterface", new object[] { cAAJUKIRENDOParam }, callback, asyncState);
        }

        // <remarks/>
        public void EndJukiRendoInterface(IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        // <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBINKAN", RequestNamespace = "http://Reams.ndensan.co.jp", ResponseNamespace = "http://Reams.ndensan.co.jp", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateKBINKAN(string strControl, AAKOBETSUINKANParamClass[] cAAKOBETSUINKANParam)
        {
            object[] results = this.Invoke("UpdateKBINKAN", new object[] { strControl, cAAKOBETSUINKANParam });
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        public IAsyncResult BeginUpdateKBINKAN(string strControl, AAKOBETSUINKANParamClass[] cAAKOBETSUINKANParam, AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateKBINKAN", new object[] { strControl, cAAKOBETSUINKANParam }, callback, asyncState);
        }

        // <remarks/>
        public int EndUpdateKBINKAN(IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBJITE", RequestNamespace = "http://Reams.ndensan.co.jp", ResponseNamespace = "http://Reams.ndensan.co.jp", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateKBJITE(string strControl, AAKOBETSUJITEParamClass[] cKOBETSUJITEParam)
        {
            object[] results = this.Invoke("UpdateKBJITE", new object[] { strControl, cKOBETSUJITEParam });
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        public IAsyncResult BeginUpdateKBJITE(string strControl, AAKOBETSUJITEParamClass[] cKOBETSUJITEParam, AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateKBJITE", new object[] { strControl, cKOBETSUJITEParam }, callback, asyncState);
        }

        // <remarks/>
        public int EndUpdateKBJITE(IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBKAIGO", RequestNamespace = "http://Reams.ndensan.co.jp", ResponseNamespace = "http://Reams.ndensan.co.jp", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateKBKAIGO(string strControl, AAKOBETSUKAIGOParamClass[] cAAKOBETSUKAIGOParam)
        {
            object[] results = this.Invoke("UpdateKBKAIGO", new object[] { strControl, cAAKOBETSUKAIGOParam });
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        public IAsyncResult BeginUpdateKBKAIGO(string strControl, AAKOBETSUKAIGOParamClass[] cAAKOBETSUKAIGOParam, AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateKBKAIGO", new object[] { strControl, cAAKOBETSUKAIGOParam }, callback, asyncState);
        }

        // <remarks/>
        public int EndUpdateKBKAIGO(IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBKOKUHO", RequestNamespace = "http://Reams.ndensan.co.jp", ResponseNamespace = "http://Reams.ndensan.co.jp", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateKBKOKUHO(string strControl, AAKOBETSUKOKUHOParamClass[] cAAKOBETSUKOKUHOParam)
        {
            object[] results = this.Invoke("UpdateKBKOKUHO", new object[] { strControl, cAAKOBETSUKOKUHOParam });
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        public IAsyncResult BeginUpdateKBKOKUHO(string strControl, AAKOBETSUKOKUHOParamClass[] cAAKOBETSUKOKUHOParam, AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateKBKOKUHO", new object[] { strControl, cAAKOBETSUKOKUHOParam }, callback, asyncState);
        }

        // <remarks/>
        public int EndUpdateKBKOKUHO(IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBNENKIN", RequestNamespace = "http://Reams.ndensan.co.jp", ResponseNamespace = "http://Reams.ndensan.co.jp", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateKBNENKIN(string strControl, AAKOBETSUNENKINParamClass[] cAAKOBETSUNENKINParam)
        {
            object[] results = this.Invoke("UpdateKBNENKIN", new object[] { strControl, cAAKOBETSUNENKINParam });
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        public IAsyncResult BeginUpdateKBNENKIN(string strControl, AAKOBETSUNENKINParamClass[] cAAKOBETSUNENKINParam, AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateKBNENKIN", new object[] { strControl, cAAKOBETSUNENKINParam }, callback, asyncState);
        }

        // <remarks/>
        public int EndUpdateKBNENKIN(IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBSENKYO", RequestNamespace = "http://Reams.ndensan.co.jp", ResponseNamespace = "http://Reams.ndensan.co.jp", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UpdateKBSENKYO(string strControl, AAKOBETSUSENKYOParamClass[] cAAKOBETSUSENKYOParam)
        {
            object[] results = this.Invoke("UpdateKBSENKYO", new object[] { strControl, cAAKOBETSUSENKYOParam });
            return Conversions.ToInteger(results[0]);
        }

        // <remarks/>
        public IAsyncResult BeginUpdateKBSENKYO(string strControl, AAKOBETSUSENKYOParamClass[] cAAKOBETSUSENKYOParam, AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("UpdateKBSENKYO", new object[] { strControl, cAAKOBETSUSENKYOParam }, callback, asyncState);
        }

        // <remarks/>
        public int EndUpdateKBSENKYO(IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return Conversions.ToInteger(results[0]);
        }
    }

    // <remarks/>
    [XmlType(Namespace = "http://Reams.ndensan.co.jp")]
    public class AAJUKIRENDOParamClass
    {

        // <remarks/>
        public string m_strShoriNichiji;

        // <remarks/>
        public string m_strShoriJiyuCD;

        // <remarks/>
        public string m_strJuminCD;

        // <remarks/>
        public string m_strMaeAtoSetPattern;

        // <remarks/>
        public string m_strMae_LinkNO;

        // <remarks/>
        public string m_strMae_RrkNO;

        // <remarks/>
        public string m_strMae_StaiCD;

        // <remarks/>
        public string m_strMae_JuminHyoCD;

        // <remarks/>
        public string m_strMae_SeiriNO;

        // <remarks/>
        public string m_strMae_ShichosonCD;

        // <remarks/>
        public string m_strMae_KyushichosonCD;

        // <remarks/>
        public string m_strMae_JuminSHU;

        // <remarks/>
        public string m_strMae_KanjiShimei;

        // <remarks/>
        public string m_strMae_KanjiKyusei;

        // <remarks/>
        public string m_strMae_KanaShimei;

        // <remarks/>
        public string m_strMae_UmareYMD;

        // <remarks/>
        public string m_strMae_UmareWMD;

        // <remarks/>
        public string m_strMae_AimaiUmareBi;

        // <remarks/>
        public string m_strMae_SeibetsuCD;

        // <remarks/>
        public string m_strMae_Seibetsu;

        // <remarks/>
        public string m_strMae_SeikiNO;

        // <remarks/>
        public string m_strMae_HyojiJun;

        // <remarks/>
        public string m_strMae_ZokugaraCD;

        // <remarks/>
        public string m_strMae_Zokugara;

        // <remarks/>
        public string m_strMae_HyojiJun2;

        // <remarks/>
        public string m_strMae_ZokugaraCD2;

        // <remarks/>
        public string m_strMae_Zokugara2;

        // <remarks/>
        public string m_strMae_StaiNusJuminCD;

        // <remarks/>
        public string m_strMae_KanjiStaiNusmei;

        // <remarks/>
        public string m_strMae_KanaStaiNusmei;

        // <remarks/>
        public string m_strMae_StaiNusJuminCD2;

        // <remarks/>
        public string m_strMae_KanjiStaiNusmei2;

        // <remarks/>
        public string m_strMae_KanaStaiNusmei2;

        // <remarks/>
        public string m_strMae_YubinNO;

        // <remarks/>
        public string m_strMae_JushoCD;

        // <remarks/>
        public string m_strMae_Jusho;

        // <remarks/>
        public string m_strMae_BanchiCD1;

        // <remarks/>
        public string m_strMae_BanchiCD2;

        // <remarks/>
        public string m_strMae_BanchiCD3;

        // <remarks/>
        public string m_strMae_Banchi;

        // <remarks/>
        public string m_strMae_KatagakiFG;

        // <remarks/>
        public string m_strMae_KatagakiCD;

        // <remarks/>
        public string m_strMae_Katagaki;

        // <remarks/>
        public string m_strMae_Renrakusaki1;

        // <remarks/>
        public string m_strMae_Renrakusaki2;

        // <remarks/>
        public string m_strMae_KjnRenrakusaki1;

        // <remarks/>
        public string m_strMae_KjnRenrakusaki2;

        // <remarks/>
        public string m_strMae_KjnRenrakusaki3;

        // <remarks/>
        public string m_strMae_Hon_ZJushoCD;

        // <remarks/>
        public string m_strMae_Hon_NJushoCD;

        // <remarks/>
        public string m_strMae_Hon_Jusho;

        // <remarks/>
        public string m_strMae_Hon_Banchi;

        // <remarks/>
        public string m_strMae_Hittosha;

        // <remarks/>
        public string m_strMae_CkinIdoYMD;

        // <remarks/>
        public string m_strMae_CkinJiyuCD;

        // <remarks/>
        public string m_strMae_CkinJiyu;

        // <remarks/>
        public string m_strMae_CkinTdkdYMD;

        // <remarks/>
        public string m_strMae_CkinTdkdTuciKB;

        // <remarks/>
        public string m_strMae_TorokuIdoYMD;

        // <remarks/>
        public string m_strMae_TorokuIdoWMD;

        // <remarks/>
        public string m_strMae_TorokuJiyuCD;

        // <remarks/>
        public string m_strMae_TorokuJiyu;

        // <remarks/>
        public string m_strMae_TorokuTdkdYMD;

        // <remarks/>
        public string m_strMae_TorokuTdkdWMD;

        // <remarks/>
        public string m_strMae_TorokuTdkdTuciKB;

        // <remarks/>
        public string m_strMae_JuteiIdoYMD;

        // <remarks/>
        public string m_strMae_JuteiIdoWMD;

        // <remarks/>
        public string m_strMae_JuteiJiyuCD;

        // <remarks/>
        public string m_strMae_JuteiJiyu;

        // <remarks/>
        public string m_strMae_JuteiTdkdYMD;

        // <remarks/>
        public string m_strMae_JuteiTdkdWMD;

        // <remarks/>
        public string m_strMae_JuteiTdkdTuciKB;

        // <remarks/>
        public string m_strMae_ShojoIdoYMD;

        // <remarks/>
        public string m_strMae_AimaiShojoIdoBi;

        // <remarks/>
        public string m_strMae_ShojoJiyuCD;

        // <remarks/>
        public string m_strMae_ShojoJiyu;

        // <remarks/>
        public string m_strMae_ShojoTdkdYMD;

        // <remarks/>
        public string m_strMae_ShojoTdkdTuciKB;

        // <remarks/>
        public string m_strMae_TenshutsuYoteiIdoYMD;

        // <remarks/>
        public string m_strMae_TenshutsuKktiIdoYMD;

        // <remarks/>
        public string m_strMae_TenshutsuKktiTuciYMD;

        // <remarks/>
        public string m_strMae_TestsuMiTdkIdoYMD;

        // <remarks/>
        public string m_strMae_TestsuMiTdkTuciYMD;

        // <remarks/>
        public string m_strMae_TenshutsunyuRiyuCD;

        // <remarks/>
        public string m_strMae_TenshutsunyuRiyu;

        // <remarks/>
        public string m_strMae_TenumaeJ_YubinNO;

        // <remarks/>
        public string m_strMae_TenumaeJ_ZJushoCD;

        // <remarks/>
        public string m_strMae_TenumaeJ_Jusho;

        // <remarks/>
        public string m_strMae_TenumaeJ_Banchi;

        // <remarks/>
        public string m_strMae_TenumaeJ_Katagaki;

        // <remarks/>
        public string m_strMae_TenumaeJ_StaiNusmei;

        // <remarks/>
        public string m_strMae_TenumaeJ_MiTdkFG;

        // <remarks/>
        public string m_strMae_SaishuJ_YubinNO;

        // <remarks/>
        public string m_strMae_SaishuJ_ZJushoCD;

        // <remarks/>
        public string m_strMae_SaishuJ_NJushoCD;

        // <remarks/>
        public string m_strMae_SaishuJ_Jusho;

        // <remarks/>
        public string m_strMae_SaishuJ_Banchi;

        // <remarks/>
        public string m_strMae_SaishuJ_Katagaki;

        // <remarks/>
        public string m_strMae_SaishuJ_StaiNusmei;

        // <remarks/>
        public string m_strMae_TenshutsuYoteiYubinNO;

        // <remarks/>
        public string m_strMae_TenshutsuYoteiZJushoCD;

        // <remarks/>
        public string m_strMae_TenshutsuYoteiJusho;

        // <remarks/>
        public string m_strMae_TenshutsuYoteiBanchi;

        // <remarks/>
        public string m_strMae_TenshutsuYoteiKatagaki;

        // <remarks/>
        public string m_strMae_TenshutsuYoteiStaiNusmei;

        // <remarks/>
        public string m_strMae_TenshutsuKktiYubinNO;

        // <remarks/>
        public string m_strMae_TenshutsuKktiZJushoCD;

        // <remarks/>
        public string m_strMae_TenshutsuKktiJusho;

        // <remarks/>
        public string m_strMae_TenshutsuKktiBanchi;

        // <remarks/>
        public string m_strMae_TenshutsuKktiKatagaki;

        // <remarks/>
        public string m_strMae_TenshutsuKktiStaiNusmei;

        // <remarks/>
        public string m_strMae_TestsuMiTdkYubinNO;

        // <remarks/>
        public string m_strMae_TestsuMiTdkZJushoCD;

        // <remarks/>
        public string m_strMae_TestsuMiTdkJusho;

        // <remarks/>
        public string m_strMae_TestsuMiTdkBanchi;

        // <remarks/>
        public string m_strMae_TestsuMiTdkKatagaki;

        // <remarks/>
        public string m_strMae_TestsuMiTdkStaiNusmei;

        // <remarks/>
        public string m_strMae_TenshutsuKktiMiTdkFG;

        // <remarks/>
        public string m_strMae_BikoYMD;

        // <remarks/>
        public string m_strMae_Biko;

        // <remarks/>
        public string m_strMae_BikoFG;

        // <remarks/>
        public string m_strMae_BikoTenshutsuKktiJushoFG;

        // <remarks/>
        public string m_strMae_UtsushiKB;

        // <remarks/>
        public string m_strMae_KaiseiatoFG;

        // <remarks/>
        public string m_strMae_KaiseimaeFG;

        // <remarks/>
        public string m_strMae_JuminhyoShichosonCD;

        // <remarks/>
        public string m_strMae_GyoseikuCD;

        // <remarks/>
        public string m_strMae_Gyoseikumei;

        // <remarks/>
        public string m_strMae_ChikuCD1;

        // <remarks/>
        public string m_strMae_Chikumei1;

        // <remarks/>
        public string m_strMae_ChikuCD2;

        // <remarks/>
        public string m_strMae_Chikumei2;

        // <remarks/>
        public string m_strMae_ChikuCD3;

        // <remarks/>
        public string m_strMae_Chikumei3;

        // <remarks/>
        public string m_strMae_TohyokuCD;

        // <remarks/>
        public string m_strMae_ShogakkokuCD;

        // <remarks/>
        public string m_strMae_ChugakkokuCD;

        // <remarks/>
        public string m_strMae_HogoshaJuminCD;

        // <remarks/>
        public string m_strMae_KanjiHogoshamei;

        // <remarks/>
        public string m_strMae_KanaHogoshamei;

        // <remarks/>
        public string m_strMae_KikaYMD;

        // <remarks/>
        public string m_strMae_KariIdoKB;

        // <remarks/>
        public string m_strMae_ShoriTeishiKB;

        // <remarks/>
        public string m_strMae_ShoriTeishiRiyu;

        // <remarks/>
        public string m_strMae_ShoriYokushiKB;

        // <remarks/>
        public string m_strMae_ShoriYokushiRiyu;

        // <remarks/>
        public string m_strMae_HanyoCD;

        // <remarks/>
        public string m_strMae_FRNmei;

        // <remarks/>
        public string m_strMae_KanaFRNmei;

        // <remarks/>
        public string m_strMae_Tsushomei;

        // <remarks/>
        public string m_strMae_KanaTsushomei;

        // <remarks/>
        public string m_strMae_KokusekiCD;

        // <remarks/>
        public string m_strMae_Kokuseki;

        // <remarks/>
        public string m_strMae_ZairyuSkakCD;

        // <remarks/>
        public string m_strMae_ZairyuSkak;

        // <remarks/>
        public string m_strMae_ZairyuKikan;

        // <remarks/>
        public string m_strMae_Zairyu_ST_YMD;

        // <remarks/>
        public string m_strMae_Zairyu_ED_YMD;

        // <remarks/>
        public string m_strAto_LinkNO;

        // <remarks/>
        public string m_strAto_RrkNO;

        // <remarks/>
        public string m_strAto_StaiCD;

        // <remarks/>
        public string m_strAto_JuminHyoCD;

        // <remarks/>
        public string m_strAto_SeiriNO;

        // <remarks/>
        public string m_strAto_ShichosonCD;

        // <remarks/>
        public string m_strAto_KyushichosonCD;

        // <remarks/>
        public string m_strAto_JuminSHU;

        // <remarks/>
        public string m_strAto_KanjiShimei;

        // <remarks/>
        public string m_strAto_KanjiKyusei;

        // <remarks/>
        public string m_strAto_KanaShimei;

        // <remarks/>
        public string m_strAto_UmareYMD;

        // <remarks/>
        public string m_strAto_UmareWMD;

        // <remarks/>
        public string m_strAto_AimaiUmareBi;

        // <remarks/>
        public string m_strAto_SeibetsuCD;

        // <remarks/>
        public string m_strAto_Seibetsu;

        // <remarks/>
        public string m_strAto_SeikiNO;

        // <remarks/>
        public string m_strAto_HyojiJun;

        // <remarks/>
        public string m_strAto_ZokugaraCD;

        // <remarks/>
        public string m_strAto_Zokugara;

        // <remarks/>
        public string m_strAto_HyojiJun2;

        // <remarks/>
        public string m_strAto_ZokugaraCD2;

        // <remarks/>
        public string m_strAto_Zokugara2;

        // <remarks/>
        public string m_strAto_StaiNusJuminCD;

        // <remarks/>
        public string m_strAto_KanjiStaiNusmei;

        // <remarks/>
        public string m_strAto_KanaStaiNusmei;

        // <remarks/>
        public string m_strAto_StaiNusJuminCD2;

        // <remarks/>
        public string m_strAto_KanjiStaiNusmei2;

        // <remarks/>
        public string m_strAto_KanaStaiNusmei2;

        // <remarks/>
        public string m_strAto_YubinNO;

        // <remarks/>
        public string m_strAto_JushoCD;

        // <remarks/>
        public string m_strAto_Jusho;

        // <remarks/>
        public string m_strAto_BanchiCD1;

        // <remarks/>
        public string m_strAto_BanchiCD2;

        // <remarks/>
        public string m_strAto_BanchiCD3;

        // <remarks/>
        public string m_strAto_Banchi;

        // <remarks/>
        public string m_strAto_KatagakiFG;

        // <remarks/>
        public string m_strAto_KatagakiCD;

        // <remarks/>
        public string m_strAto_Katagaki;

        // <remarks/>
        public string m_strAto_Renrakusaki1;

        // <remarks/>
        public string m_strAto_Renrakusaki2;

        // <remarks/>
        public string m_strAto_KjnRenrakusaki1;

        // <remarks/>
        public string m_strAto_KjnRenrakusaki2;

        // <remarks/>
        public string m_strAto_KjnRenrakusaki3;

        // <remarks/>
        public string m_strAto_Hon_ZJushoCD;

        // <remarks/>
        public string m_strAto_Hon_NJushoCD;

        // <remarks/>
        public string m_strAto_Hon_Jusho;

        // <remarks/>
        public string m_strAto_Hon_Banchi;

        // <remarks/>
        public string m_strAto_Hittosha;

        // <remarks/>
        public string m_strAto_CkinIdoYMD;

        // <remarks/>
        public string m_strAto_CkinJiyuCD;

        // <remarks/>
        public string m_strAto_CkinJiyu;

        // <remarks/>
        public string m_strAto_CkinTdkdYMD;

        // <remarks/>
        public string m_strAto_CkinTdkdTuciKB;

        // <remarks/>
        public string m_strAto_TorokuIdoYMD;

        // <remarks/>
        public string m_strAto_TorokuIdoWMD;

        // <remarks/>
        public string m_strAto_TorokuJiyuCD;

        // <remarks/>
        public string m_strAto_TorokuJiyu;

        // <remarks/>
        public string m_strAto_TorokuTdkdYMD;

        // <remarks/>
        public string m_strAto_TorokuTdkdWMD;

        // <remarks/>
        public string m_strAto_TorokuTdkdTuciKB;

        // <remarks/>
        public string m_strAto_JuteiIdoYMD;

        // <remarks/>
        public string m_strAto_JuteiIdoWMD;

        // <remarks/>
        public string m_strAto_JuteiJiyuCD;

        // <remarks/>
        public string m_strAto_JuteiJiyu;

        // <remarks/>
        public string m_strAto_JuteiTdkdYMD;

        // <remarks/>
        public string m_strAto_JuteiTdkdWMD;

        // <remarks/>
        public string m_strAto_JuteiTdkdTuciKB;

        // <remarks/>
        public string m_strAto_ShojoIdoYMD;

        // <remarks/>
        public string m_strAto_AimaiShojoIdoBi;

        // <remarks/>
        public string m_strAto_ShojoJiyuCD;

        // <remarks/>
        public string m_strAto_ShojoJiyu;

        // <remarks/>
        public string m_strAto_ShojoTdkdYMD;

        // <remarks/>
        public string m_strAto_ShojoTdkdTuciKB;

        // <remarks/>
        public string m_strAto_TenshutsuYoteiIdoYMD;

        // <remarks/>
        public string m_strAto_TenshutsuKktiIdoYMD;

        // <remarks/>
        public string m_strAto_TenshutsuKktiTuciYMD;

        // <remarks/>
        public string m_strAto_TestsuMiTdkIdoYMD;

        // <remarks/>
        public string m_strAto_TestsuMiTdkTuciYMD;

        // <remarks/>
        public string m_strAto_TenshutsunyuRiyuCD;

        // <remarks/>
        public string m_strAto_TenshutsunyuRiyu;

        // <remarks/>
        public string m_strAto_TenumaeJ_YubinNO;

        // <remarks/>
        public string m_strAto_TenumaeJ_ZJushoCD;

        // <remarks/>
        public string m_strAto_TenumaeJ_Jusho;

        // <remarks/>
        public string m_strAto_TenumaeJ_Banchi;

        // <remarks/>
        public string m_strAto_TenumaeJ_Katagaki;

        // <remarks/>
        public string m_strAto_TenumaeJ_StaiNusmei;

        // <remarks/>
        public string m_strAto_TenumaeJ_MiTdkFG;

        // <remarks/>
        public string m_strAto_SaishuJ_YubinNO;

        // <remarks/>
        public string m_strAto_SaishuJ_ZJushoCD;

        // <remarks/>
        public string m_strAto_SaishuJ_NJushoCD;

        // <remarks/>
        public string m_strAto_SaishuJ_Jusho;

        // <remarks/>
        public string m_strAto_SaishuJ_Banchi;

        // <remarks/>
        public string m_strAto_SaishuJ_Katagaki;

        // <remarks/>
        public string m_strAto_SaishuJ_StaiNusmei;

        // <remarks/>
        public string m_strAto_TenshutsuYoteiYubinNO;

        // <remarks/>
        public string m_strAto_TenshutsuYoteiZJushoCD;

        // <remarks/>
        public string m_strAto_TenshutsuYoteiJusho;

        // <remarks/>
        public string m_strAto_TenshutsuYoteiBanchi;

        // <remarks/>
        public string m_strAto_TenshutsuYoteiKatagaki;

        // <remarks/>
        public string m_strAto_TenshutsuYoteiStaiNusmei;

        // <remarks/>
        public string m_strAto_TenshutsuKktiYubinNO;

        // <remarks/>
        public string m_strAto_TenshutsuKktiZJushoCD;

        // <remarks/>
        public string m_strAto_TenshutsuKktiJusho;

        // <remarks/>
        public string m_strAto_TenshutsuKktiBanchi;

        // <remarks/>
        public string m_strAto_TenshutsuKktiKatagaki;

        // <remarks/>
        public string m_strAto_TenshutsuKktiStaiNusmei;

        // <remarks/>
        public string m_strAto_TestsuMiTdkYubinNO;

        // <remarks/>
        public string m_strAto_TestsuMiTdkZJushoCD;

        // <remarks/>
        public string m_strAto_TestsuMiTdkJusho;

        // <remarks/>
        public string m_strAto_TestsuMiTdkBanchi;

        // <remarks/>
        public string m_strAto_TestsuMiTdkKatagaki;

        // <remarks/>
        public string m_strAto_TestsuMiTdkStaiNusmei;

        // <remarks/>
        public string m_strAto_TenshutsuKktiMiTdkFG;

        // <remarks/>
        public string m_strAto_BikoYMD;

        // <remarks/>
        public string m_strAto_Biko;

        // <remarks/>
        public string m_strAto_BikoFG;

        // <remarks/>
        public string m_strAto_BikoTenshutsuKktiJushoFG;

        // <remarks/>
        public string m_strAto_UtsushiKB;

        // <remarks/>
        public string m_strAto_KaiseiatoFG;

        // <remarks/>
        public string m_strAto_KaiseimaeFG;

        // <remarks/>
        public string m_strAto_JuminhyoShichosonCD;

        // <remarks/>
        public string m_strAto_GyoseikuCD;

        // <remarks/>
        public string m_strAto_Gyoseikumei;

        // <remarks/>
        public string m_strAto_ChikuCD1;

        // <remarks/>
        public string m_strAto_Chikumei1;

        // <remarks/>
        public string m_strAto_ChikuCD2;

        // <remarks/>
        public string m_strAto_Chikumei2;

        // <remarks/>
        public string m_strAto_ChikuCD3;

        // <remarks/>
        public string m_strAto_Chikumei3;

        // <remarks/>
        public string m_strAto_TohyokuCD;

        // <remarks/>
        public string m_strAto_ShogakkokuCD;

        // <remarks/>
        public string m_strAto_ChugakkokuCD;

        // <remarks/>
        public string m_strAto_HogoshaJuminCD;

        // <remarks/>
        public string m_strAto_KanjiHogoshamei;

        // <remarks/>
        public string m_strAto_KanaHogoshamei;

        // <remarks/>
        public string m_strAto_KikaYMD;

        // <remarks/>
        public string m_strAto_KariIdoKB;

        // <remarks/>
        public string m_strAto_ShoriTeishiKB;

        // <remarks/>
        public string m_strAto_ShoriTeishiRiyu;

        // <remarks/>
        public string m_strAto_ShoriYokushiKB;

        // <remarks/>
        public string m_strAto_ShoriYokushiRiyu;

        // <remarks/>
        public string m_strAto_HanyoCD;

        // <remarks/>
        public string m_strAto_FRNmei;

        // <remarks/>
        public string m_strAto_KanaFRNmei;

        // <remarks/>
        public string m_strAto_Tsushomei;

        // <remarks/>
        public string m_strAto_KanaTsushomei;

        // <remarks/>
        public string m_strAto_KokusekiCD;

        // <remarks/>
        public string m_strAto_Kokuseki;

        // <remarks/>
        public string m_strAto_ZairyuSkakCD;

        // <remarks/>
        public string m_strAto_ZairyuSkak;

        // <remarks/>
        public string m_strAto_ZairyuKikan;

        // <remarks/>
        public string m_strAto_Zairyu_ST_YMD;

        // <remarks/>
        public string m_strAto_Zairyu_ED_YMD;
    }

    // <remarks/>
    [XmlType(Namespace = "http://Reams.ndensan.co.jp")]
    public class AAKOBETSUSENKYOParamClass
    {

        // <remarks/>
        public string m_strJuminCD;

        // <remarks/>
        public string m_strSenkyoShikakuKB;

        // <remarks/>
        public string m_strTohyokuCD;
    }

    // <remarks/>
    [XmlType(Namespace = "http://Reams.ndensan.co.jp")]
    public class AAKOBETSUNENKINParamClass
    {

        // <remarks/>
        public string m_strJUMINCD;

        // <remarks/>
        public string m_strKSNENKNNO;

        // <remarks/>
        public string m_strSKAKSHUTKYMD;

        // <remarks/>
        public string m_strSKAKSHUTKSHU;

        // <remarks/>
        public string m_strSKAKSHUTKRIYUCD;

        // <remarks/>
        public string m_strSKAKSSHTSYMD;

        // <remarks/>
        public string m_strSKAKSSHTSRIYUCD;

        // <remarks/>
        public string m_strJKYNENKNKIGO1;

        // <remarks/>
        public string m_strJKYNENKNNO1;

        // <remarks/>
        public string m_strJKYNENKNSHU1;

        // <remarks/>
        public string m_strJKYNENKNEDABAN1;

        // <remarks/>
        public string m_strJKYNENKNKB1;

        // <remarks/>
        public string m_strJKYNENKNKIGO2;

        // <remarks/>
        public string m_strJKYNENKNNO2;

        // <remarks/>
        public string m_strJKYNENKNSHU2;

        // <remarks/>
        public string m_strJKYNENKNEDABAN2;

        // <remarks/>
        public string m_strJKYNENKNKB2;

        // <remarks/>
        public string m_strJKYNENKNKIGO3;

        // <remarks/>
        public string m_strJKYNENKNNO3;

        // <remarks/>
        public string m_strJKYNENKNSHU3;

        // <remarks/>
        public string m_strJKYNENKNEDABAN3;

        // <remarks/>
        public string m_strJKYNENKNKB3;
    }

    // <remarks/>
    [XmlType(Namespace = "http://Reams.ndensan.co.jp")]
    public class AAKOBETSUKOKUHOParamClass
    {

        // <remarks/>
        public string m_strJUMINCD;

        // <remarks/>
        public string m_strKOKUHONO;

        // <remarks/>
        public string m_strKOKUHOSHIKAKUKB;

        // <remarks/>
        public string m_strKOKUHOSHIKAKUKBMEISHO;

        // <remarks/>
        public string m_strKOKUHOSHIKAKUKBRYAKUSHO;

        // <remarks/>
        public string m_strKOKUHOGAKUENKB;

        // <remarks/>
        public string m_strKOKUHOGAKUENKBMEISHO;

        // <remarks/>
        public string m_strKOKUHOGAKUENKBRYAKUSHO;

        // <remarks/>
        public string m_strKOKUHOSHUTOKUYMD;

        // <remarks/>
        public string m_strKOKUHOSOSHITSUYMD;

        // <remarks/>
        public string m_strKOKUHOTISHKKB;

        // <remarks/>
        public string m_strKOKUHOTISHKKBMEISHO;

        // <remarks/>
        public string m_strKOKUHOTISHKKBRYAKUSHO;

        // <remarks/>
        public string m_strKOKUHOTISHKHONHIKB;

        // <remarks/>
        public string m_strKOKUHOTISHKHONHIKBMEISHO;

        // <remarks/>
        public string m_strKOKUHOTISHKHONHIKBRYAKUSHO;

        // <remarks/>
        public string m_strKOKUHOTISHKGAITOYMD;

        // <remarks/>
        public string m_strKOKUHOTISHKHIGAITOYMD;

        // <remarks/>
        public string m_strKOKUHOHOKENSHOKIGO;

        // <remarks/>
        public string m_strKOKUHOHOKENSHONO;
    }

    // <remarks/>
    [XmlType(Namespace = "http://Reams.ndensan.co.jp")]
    public class AAKOBETSUKAIGOParamClass
    {

        // <remarks/>
        public string m_strJUMINCD;

        // <remarks/>
        public string m_strHIHKNSHANO;

        // <remarks/>
        public string m_strSKAKSHUTKYMD;

        // <remarks/>
        public string m_strSKAKSSHTSYMD;

        // <remarks/>
        public string m_strSKAKHIHOKENSHAKB;

        // <remarks/>
        public string m_strJUSHOCHITKRIKB;

        // <remarks/>
        public string m_strJUKYUSHAKB;

        // <remarks/>
        public string m_strYOKAIGJOTAIKBCD;

        // <remarks/>
        public string m_strKAIGSKAKKB;

        // <remarks/>
        public string m_strNINTEIKAISHIYMD;

        // <remarks/>
        public string m_strNINTEISHURYOYMD;

        // <remarks/>
        public string m_strJUKYUNINTEIYMD;

        // <remarks/>
        public string m_strJUKYUNINTEITORIKESHIYMD;
    }

    // <remarks/>
    [XmlType(Namespace = "http://Reams.ndensan.co.jp")]
    public class AAKOBETSUJITEParamClass
    {

        // <remarks/>
        public string m_strJUMINCD;

        // <remarks/>
        public string m_strHIYOKB;

        // <remarks/>
        public string m_strJIDOTEATESTYM;

        // <remarks/>
        public string m_strJIDOTEATEEDYM;
    }

    // <remarks/>
    [XmlType(Namespace = "http://Reams.ndensan.co.jp")]
    public class AAKOBETSUINKANParamClass
    {

        // <remarks/>
        public string m_strJUMINCD;

        // <remarks/>
        public string m_strINKANNO;

        // <remarks/>
        public string m_strINKANTOROKUKB;
    }
}