'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.288
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'このソース コードは Microsoft.VSDesigner、バージョン 1.0.3705.288 によって自動生成されました。
'
Namespace localhost
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="AACommonBSClassSoap", [Namespace]:="http://Reams.ndensan.co.jp")>  _
    Public Class AACommonBSClass
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/Densan/Reams/AA/AA001BS/AACommonBSClass.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/JukiRendoInterface", RequestNamespace:="http://Reams.ndensan.co.jp", ResponseNamespace:="http://Reams.ndensan.co.jp", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub JukiRendoInterface(ByVal cAAJUKIRENDOParam As AAJUKIRENDOParamClass)
            Me.Invoke("JukiRendoInterface", New Object() {cAAJUKIRENDOParam})
        End Sub
        
        '<remarks/>
        Public Function BeginJukiRendoInterface(ByVal cAAJUKIRENDOParam As AAJUKIRENDOParamClass, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("JukiRendoInterface", New Object() {cAAJUKIRENDOParam}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Sub EndJukiRendoInterface(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBINKAN", RequestNamespace:="http://Reams.ndensan.co.jp", ResponseNamespace:="http://Reams.ndensan.co.jp", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateKBINKAN(ByVal strControl As String, ByVal cAAKOBETSUINKANParam() As AAKOBETSUINKANParamClass) As Integer
            Dim results() As Object = Me.Invoke("UpdateKBINKAN", New Object() {strControl, cAAKOBETSUINKANParam})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateKBINKAN(ByVal strControl As String, ByVal cAAKOBETSUINKANParam() As AAKOBETSUINKANParamClass, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateKBINKAN", New Object() {strControl, cAAKOBETSUINKANParam}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateKBINKAN(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBJITE", RequestNamespace:="http://Reams.ndensan.co.jp", ResponseNamespace:="http://Reams.ndensan.co.jp", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateKBJITE(ByVal strControl As String, ByVal cKOBETSUJITEParam() As AAKOBETSUJITEParamClass) As Integer
            Dim results() As Object = Me.Invoke("UpdateKBJITE", New Object() {strControl, cKOBETSUJITEParam})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateKBJITE(ByVal strControl As String, ByVal cKOBETSUJITEParam() As AAKOBETSUJITEParamClass, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateKBJITE", New Object() {strControl, cKOBETSUJITEParam}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateKBJITE(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBKAIGO", RequestNamespace:="http://Reams.ndensan.co.jp", ResponseNamespace:="http://Reams.ndensan.co.jp", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateKBKAIGO(ByVal strControl As String, ByVal cAAKOBETSUKAIGOParam() As AAKOBETSUKAIGOParamClass) As Integer
            Dim results() As Object = Me.Invoke("UpdateKBKAIGO", New Object() {strControl, cAAKOBETSUKAIGOParam})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateKBKAIGO(ByVal strControl As String, ByVal cAAKOBETSUKAIGOParam() As AAKOBETSUKAIGOParamClass, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateKBKAIGO", New Object() {strControl, cAAKOBETSUKAIGOParam}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateKBKAIGO(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBKOKUHO", RequestNamespace:="http://Reams.ndensan.co.jp", ResponseNamespace:="http://Reams.ndensan.co.jp", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateKBKOKUHO(ByVal strControl As String, ByVal cAAKOBETSUKOKUHOParam() As AAKOBETSUKOKUHOParamClass) As Integer
            Dim results() As Object = Me.Invoke("UpdateKBKOKUHO", New Object() {strControl, cAAKOBETSUKOKUHOParam})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateKBKOKUHO(ByVal strControl As String, ByVal cAAKOBETSUKOKUHOParam() As AAKOBETSUKOKUHOParamClass, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateKBKOKUHO", New Object() {strControl, cAAKOBETSUKOKUHOParam}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateKBKOKUHO(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBNENKIN", RequestNamespace:="http://Reams.ndensan.co.jp", ResponseNamespace:="http://Reams.ndensan.co.jp", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateKBNENKIN(ByVal strControl As String, ByVal cAAKOBETSUNENKINParam() As AAKOBETSUNENKINParamClass) As Integer
            Dim results() As Object = Me.Invoke("UpdateKBNENKIN", New Object() {strControl, cAAKOBETSUNENKINParam})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateKBNENKIN(ByVal strControl As String, ByVal cAAKOBETSUNENKINParam() As AAKOBETSUNENKINParamClass, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateKBNENKIN", New Object() {strControl, cAAKOBETSUNENKINParam}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateKBNENKIN(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://Reams.ndensan.co.jp/UpdateKBSENKYO", RequestNamespace:="http://Reams.ndensan.co.jp", ResponseNamespace:="http://Reams.ndensan.co.jp", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateKBSENKYO(ByVal strControl As String, ByVal cAAKOBETSUSENKYOParam() As AAKOBETSUSENKYOParamClass) As Integer
            Dim results() As Object = Me.Invoke("UpdateKBSENKYO", New Object() {strControl, cAAKOBETSUSENKYOParam})
            Return CType(results(0),Integer)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateKBSENKYO(ByVal strControl As String, ByVal cAAKOBETSUSENKYOParam() As AAKOBETSUSENKYOParamClass, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateKBSENKYO", New Object() {strControl, cAAKOBETSUSENKYOParam}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateKBSENKYO(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://Reams.ndensan.co.jp")>  _
    Public Class AAJUKIRENDOParamClass
        
        '<remarks/>
        Public m_strShoriNichiji As String
        
        '<remarks/>
        Public m_strShoriJiyuCD As String
        
        '<remarks/>
        Public m_strJuminCD As String
        
        '<remarks/>
        Public m_strMaeAtoSetPattern As String
        
        '<remarks/>
        Public m_strMae_LinkNO As String
        
        '<remarks/>
        Public m_strMae_RrkNO As String
        
        '<remarks/>
        Public m_strMae_StaiCD As String
        
        '<remarks/>
        Public m_strMae_JuminHyoCD As String
        
        '<remarks/>
        Public m_strMae_SeiriNO As String
        
        '<remarks/>
        Public m_strMae_ShichosonCD As String
        
        '<remarks/>
        Public m_strMae_KyushichosonCD As String
        
        '<remarks/>
        Public m_strMae_JuminSHU As String
        
        '<remarks/>
        Public m_strMae_KanjiShimei As String
        
        '<remarks/>
        Public m_strMae_KanjiKyusei As String
        
        '<remarks/>
        Public m_strMae_KanaShimei As String
        
        '<remarks/>
        Public m_strMae_UmareYMD As String
        
        '<remarks/>
        Public m_strMae_UmareWMD As String
        
        '<remarks/>
        Public m_strMae_AimaiUmareBi As String
        
        '<remarks/>
        Public m_strMae_SeibetsuCD As String
        
        '<remarks/>
        Public m_strMae_Seibetsu As String
        
        '<remarks/>
        Public m_strMae_SeikiNO As String
        
        '<remarks/>
        Public m_strMae_HyojiJun As String
        
        '<remarks/>
        Public m_strMae_ZokugaraCD As String
        
        '<remarks/>
        Public m_strMae_Zokugara As String
        
        '<remarks/>
        Public m_strMae_HyojiJun2 As String
        
        '<remarks/>
        Public m_strMae_ZokugaraCD2 As String
        
        '<remarks/>
        Public m_strMae_Zokugara2 As String
        
        '<remarks/>
        Public m_strMae_StaiNusJuminCD As String
        
        '<remarks/>
        Public m_strMae_KanjiStaiNusmei As String
        
        '<remarks/>
        Public m_strMae_KanaStaiNusmei As String
        
        '<remarks/>
        Public m_strMae_StaiNusJuminCD2 As String
        
        '<remarks/>
        Public m_strMae_KanjiStaiNusmei2 As String
        
        '<remarks/>
        Public m_strMae_KanaStaiNusmei2 As String
        
        '<remarks/>
        Public m_strMae_YubinNO As String
        
        '<remarks/>
        Public m_strMae_JushoCD As String
        
        '<remarks/>
        Public m_strMae_Jusho As String
        
        '<remarks/>
        Public m_strMae_BanchiCD1 As String
        
        '<remarks/>
        Public m_strMae_BanchiCD2 As String
        
        '<remarks/>
        Public m_strMae_BanchiCD3 As String
        
        '<remarks/>
        Public m_strMae_Banchi As String
        
        '<remarks/>
        Public m_strMae_KatagakiFG As String
        
        '<remarks/>
        Public m_strMae_KatagakiCD As String
        
        '<remarks/>
        Public m_strMae_Katagaki As String
        
        '<remarks/>
        Public m_strMae_Renrakusaki1 As String
        
        '<remarks/>
        Public m_strMae_Renrakusaki2 As String
        
        '<remarks/>
        Public m_strMae_KjnRenrakusaki1 As String
        
        '<remarks/>
        Public m_strMae_KjnRenrakusaki2 As String
        
        '<remarks/>
        Public m_strMae_KjnRenrakusaki3 As String
        
        '<remarks/>
        Public m_strMae_Hon_ZJushoCD As String
        
        '<remarks/>
        Public m_strMae_Hon_NJushoCD As String
        
        '<remarks/>
        Public m_strMae_Hon_Jusho As String
        
        '<remarks/>
        Public m_strMae_Hon_Banchi As String
        
        '<remarks/>
        Public m_strMae_Hittosha As String
        
        '<remarks/>
        Public m_strMae_CkinIdoYMD As String
        
        '<remarks/>
        Public m_strMae_CkinJiyuCD As String
        
        '<remarks/>
        Public m_strMae_CkinJiyu As String
        
        '<remarks/>
        Public m_strMae_CkinTdkdYMD As String
        
        '<remarks/>
        Public m_strMae_CkinTdkdTuciKB As String
        
        '<remarks/>
        Public m_strMae_TorokuIdoYMD As String
        
        '<remarks/>
        Public m_strMae_TorokuIdoWMD As String
        
        '<remarks/>
        Public m_strMae_TorokuJiyuCD As String
        
        '<remarks/>
        Public m_strMae_TorokuJiyu As String
        
        '<remarks/>
        Public m_strMae_TorokuTdkdYMD As String
        
        '<remarks/>
        Public m_strMae_TorokuTdkdWMD As String
        
        '<remarks/>
        Public m_strMae_TorokuTdkdTuciKB As String
        
        '<remarks/>
        Public m_strMae_JuteiIdoYMD As String
        
        '<remarks/>
        Public m_strMae_JuteiIdoWMD As String
        
        '<remarks/>
        Public m_strMae_JuteiJiyuCD As String
        
        '<remarks/>
        Public m_strMae_JuteiJiyu As String
        
        '<remarks/>
        Public m_strMae_JuteiTdkdYMD As String
        
        '<remarks/>
        Public m_strMae_JuteiTdkdWMD As String
        
        '<remarks/>
        Public m_strMae_JuteiTdkdTuciKB As String
        
        '<remarks/>
        Public m_strMae_ShojoIdoYMD As String
        
        '<remarks/>
        Public m_strMae_AimaiShojoIdoBi As String
        
        '<remarks/>
        Public m_strMae_ShojoJiyuCD As String
        
        '<remarks/>
        Public m_strMae_ShojoJiyu As String
        
        '<remarks/>
        Public m_strMae_ShojoTdkdYMD As String
        
        '<remarks/>
        Public m_strMae_ShojoTdkdTuciKB As String
        
        '<remarks/>
        Public m_strMae_TenshutsuYoteiIdoYMD As String
        
        '<remarks/>
        Public m_strMae_TenshutsuKktiIdoYMD As String
        
        '<remarks/>
        Public m_strMae_TenshutsuKktiTuciYMD As String
        
        '<remarks/>
        Public m_strMae_TestsuMiTdkIdoYMD As String
        
        '<remarks/>
        Public m_strMae_TestsuMiTdkTuciYMD As String
        
        '<remarks/>
        Public m_strMae_TenshutsunyuRiyuCD As String
        
        '<remarks/>
        Public m_strMae_TenshutsunyuRiyu As String
        
        '<remarks/>
        Public m_strMae_TenumaeJ_YubinNO As String
        
        '<remarks/>
        Public m_strMae_TenumaeJ_ZJushoCD As String
        
        '<remarks/>
        Public m_strMae_TenumaeJ_Jusho As String
        
        '<remarks/>
        Public m_strMae_TenumaeJ_Banchi As String
        
        '<remarks/>
        Public m_strMae_TenumaeJ_Katagaki As String
        
        '<remarks/>
        Public m_strMae_TenumaeJ_StaiNusmei As String
        
        '<remarks/>
        Public m_strMae_TenumaeJ_MiTdkFG As String
        
        '<remarks/>
        Public m_strMae_SaishuJ_YubinNO As String
        
        '<remarks/>
        Public m_strMae_SaishuJ_ZJushoCD As String
        
        '<remarks/>
        Public m_strMae_SaishuJ_NJushoCD As String
        
        '<remarks/>
        Public m_strMae_SaishuJ_Jusho As String
        
        '<remarks/>
        Public m_strMae_SaishuJ_Banchi As String
        
        '<remarks/>
        Public m_strMae_SaishuJ_Katagaki As String
        
        '<remarks/>
        Public m_strMae_SaishuJ_StaiNusmei As String
        
        '<remarks/>
        Public m_strMae_TenshutsuYoteiYubinNO As String
        
        '<remarks/>
        Public m_strMae_TenshutsuYoteiZJushoCD As String
        
        '<remarks/>
        Public m_strMae_TenshutsuYoteiJusho As String
        
        '<remarks/>
        Public m_strMae_TenshutsuYoteiBanchi As String
        
        '<remarks/>
        Public m_strMae_TenshutsuYoteiKatagaki As String
        
        '<remarks/>
        Public m_strMae_TenshutsuYoteiStaiNusmei As String
        
        '<remarks/>
        Public m_strMae_TenshutsuKktiYubinNO As String
        
        '<remarks/>
        Public m_strMae_TenshutsuKktiZJushoCD As String
        
        '<remarks/>
        Public m_strMae_TenshutsuKktiJusho As String
        
        '<remarks/>
        Public m_strMae_TenshutsuKktiBanchi As String
        
        '<remarks/>
        Public m_strMae_TenshutsuKktiKatagaki As String
        
        '<remarks/>
        Public m_strMae_TenshutsuKktiStaiNusmei As String
        
        '<remarks/>
        Public m_strMae_TestsuMiTdkYubinNO As String
        
        '<remarks/>
        Public m_strMae_TestsuMiTdkZJushoCD As String
        
        '<remarks/>
        Public m_strMae_TestsuMiTdkJusho As String
        
        '<remarks/>
        Public m_strMae_TestsuMiTdkBanchi As String
        
        '<remarks/>
        Public m_strMae_TestsuMiTdkKatagaki As String
        
        '<remarks/>
        Public m_strMae_TestsuMiTdkStaiNusmei As String
        
        '<remarks/>
        Public m_strMae_TenshutsuKktiMiTdkFG As String
        
        '<remarks/>
        Public m_strMae_BikoYMD As String
        
        '<remarks/>
        Public m_strMae_Biko As String
        
        '<remarks/>
        Public m_strMae_BikoFG As String
        
        '<remarks/>
        Public m_strMae_BikoTenshutsuKktiJushoFG As String
        
        '<remarks/>
        Public m_strMae_UtsushiKB As String
        
        '<remarks/>
        Public m_strMae_KaiseiatoFG As String
        
        '<remarks/>
        Public m_strMae_KaiseimaeFG As String
        
        '<remarks/>
        Public m_strMae_JuminhyoShichosonCD As String
        
        '<remarks/>
        Public m_strMae_GyoseikuCD As String
        
        '<remarks/>
        Public m_strMae_Gyoseikumei As String
        
        '<remarks/>
        Public m_strMae_ChikuCD1 As String
        
        '<remarks/>
        Public m_strMae_Chikumei1 As String
        
        '<remarks/>
        Public m_strMae_ChikuCD2 As String
        
        '<remarks/>
        Public m_strMae_Chikumei2 As String
        
        '<remarks/>
        Public m_strMae_ChikuCD3 As String
        
        '<remarks/>
        Public m_strMae_Chikumei3 As String
        
        '<remarks/>
        Public m_strMae_TohyokuCD As String
        
        '<remarks/>
        Public m_strMae_ShogakkokuCD As String
        
        '<remarks/>
        Public m_strMae_ChugakkokuCD As String
        
        '<remarks/>
        Public m_strMae_HogoshaJuminCD As String
        
        '<remarks/>
        Public m_strMae_KanjiHogoshamei As String
        
        '<remarks/>
        Public m_strMae_KanaHogoshamei As String
        
        '<remarks/>
        Public m_strMae_KikaYMD As String
        
        '<remarks/>
        Public m_strMae_KariIdoKB As String
        
        '<remarks/>
        Public m_strMae_ShoriTeishiKB As String
        
        '<remarks/>
        Public m_strMae_ShoriTeishiRiyu As String
        
        '<remarks/>
        Public m_strMae_ShoriYokushiKB As String
        
        '<remarks/>
        Public m_strMae_ShoriYokushiRiyu As String
        
        '<remarks/>
        Public m_strMae_HanyoCD As String
        
        '<remarks/>
        Public m_strMae_FRNmei As String
        
        '<remarks/>
        Public m_strMae_KanaFRNmei As String
        
        '<remarks/>
        Public m_strMae_Tsushomei As String
        
        '<remarks/>
        Public m_strMae_KanaTsushomei As String
        
        '<remarks/>
        Public m_strMae_KokusekiCD As String
        
        '<remarks/>
        Public m_strMae_Kokuseki As String
        
        '<remarks/>
        Public m_strMae_ZairyuSkakCD As String
        
        '<remarks/>
        Public m_strMae_ZairyuSkak As String
        
        '<remarks/>
        Public m_strMae_ZairyuKikan As String
        
        '<remarks/>
        Public m_strMae_Zairyu_ST_YMD As String
        
        '<remarks/>
        Public m_strMae_Zairyu_ED_YMD As String
        
        '<remarks/>
        Public m_strAto_LinkNO As String
        
        '<remarks/>
        Public m_strAto_RrkNO As String
        
        '<remarks/>
        Public m_strAto_StaiCD As String
        
        '<remarks/>
        Public m_strAto_JuminHyoCD As String
        
        '<remarks/>
        Public m_strAto_SeiriNO As String
        
        '<remarks/>
        Public m_strAto_ShichosonCD As String
        
        '<remarks/>
        Public m_strAto_KyushichosonCD As String
        
        '<remarks/>
        Public m_strAto_JuminSHU As String
        
        '<remarks/>
        Public m_strAto_KanjiShimei As String
        
        '<remarks/>
        Public m_strAto_KanjiKyusei As String
        
        '<remarks/>
        Public m_strAto_KanaShimei As String
        
        '<remarks/>
        Public m_strAto_UmareYMD As String
        
        '<remarks/>
        Public m_strAto_UmareWMD As String
        
        '<remarks/>
        Public m_strAto_AimaiUmareBi As String
        
        '<remarks/>
        Public m_strAto_SeibetsuCD As String
        
        '<remarks/>
        Public m_strAto_Seibetsu As String
        
        '<remarks/>
        Public m_strAto_SeikiNO As String
        
        '<remarks/>
        Public m_strAto_HyojiJun As String
        
        '<remarks/>
        Public m_strAto_ZokugaraCD As String
        
        '<remarks/>
        Public m_strAto_Zokugara As String
        
        '<remarks/>
        Public m_strAto_HyojiJun2 As String
        
        '<remarks/>
        Public m_strAto_ZokugaraCD2 As String
        
        '<remarks/>
        Public m_strAto_Zokugara2 As String
        
        '<remarks/>
        Public m_strAto_StaiNusJuminCD As String
        
        '<remarks/>
        Public m_strAto_KanjiStaiNusmei As String
        
        '<remarks/>
        Public m_strAto_KanaStaiNusmei As String
        
        '<remarks/>
        Public m_strAto_StaiNusJuminCD2 As String
        
        '<remarks/>
        Public m_strAto_KanjiStaiNusmei2 As String
        
        '<remarks/>
        Public m_strAto_KanaStaiNusmei2 As String
        
        '<remarks/>
        Public m_strAto_YubinNO As String
        
        '<remarks/>
        Public m_strAto_JushoCD As String
        
        '<remarks/>
        Public m_strAto_Jusho As String
        
        '<remarks/>
        Public m_strAto_BanchiCD1 As String
        
        '<remarks/>
        Public m_strAto_BanchiCD2 As String
        
        '<remarks/>
        Public m_strAto_BanchiCD3 As String
        
        '<remarks/>
        Public m_strAto_Banchi As String
        
        '<remarks/>
        Public m_strAto_KatagakiFG As String
        
        '<remarks/>
        Public m_strAto_KatagakiCD As String
        
        '<remarks/>
        Public m_strAto_Katagaki As String
        
        '<remarks/>
        Public m_strAto_Renrakusaki1 As String
        
        '<remarks/>
        Public m_strAto_Renrakusaki2 As String
        
        '<remarks/>
        Public m_strAto_KjnRenrakusaki1 As String
        
        '<remarks/>
        Public m_strAto_KjnRenrakusaki2 As String
        
        '<remarks/>
        Public m_strAto_KjnRenrakusaki3 As String
        
        '<remarks/>
        Public m_strAto_Hon_ZJushoCD As String
        
        '<remarks/>
        Public m_strAto_Hon_NJushoCD As String
        
        '<remarks/>
        Public m_strAto_Hon_Jusho As String
        
        '<remarks/>
        Public m_strAto_Hon_Banchi As String
        
        '<remarks/>
        Public m_strAto_Hittosha As String
        
        '<remarks/>
        Public m_strAto_CkinIdoYMD As String
        
        '<remarks/>
        Public m_strAto_CkinJiyuCD As String
        
        '<remarks/>
        Public m_strAto_CkinJiyu As String
        
        '<remarks/>
        Public m_strAto_CkinTdkdYMD As String
        
        '<remarks/>
        Public m_strAto_CkinTdkdTuciKB As String
        
        '<remarks/>
        Public m_strAto_TorokuIdoYMD As String
        
        '<remarks/>
        Public m_strAto_TorokuIdoWMD As String
        
        '<remarks/>
        Public m_strAto_TorokuJiyuCD As String
        
        '<remarks/>
        Public m_strAto_TorokuJiyu As String
        
        '<remarks/>
        Public m_strAto_TorokuTdkdYMD As String
        
        '<remarks/>
        Public m_strAto_TorokuTdkdWMD As String
        
        '<remarks/>
        Public m_strAto_TorokuTdkdTuciKB As String
        
        '<remarks/>
        Public m_strAto_JuteiIdoYMD As String
        
        '<remarks/>
        Public m_strAto_JuteiIdoWMD As String
        
        '<remarks/>
        Public m_strAto_JuteiJiyuCD As String
        
        '<remarks/>
        Public m_strAto_JuteiJiyu As String
        
        '<remarks/>
        Public m_strAto_JuteiTdkdYMD As String
        
        '<remarks/>
        Public m_strAto_JuteiTdkdWMD As String
        
        '<remarks/>
        Public m_strAto_JuteiTdkdTuciKB As String
        
        '<remarks/>
        Public m_strAto_ShojoIdoYMD As String
        
        '<remarks/>
        Public m_strAto_AimaiShojoIdoBi As String
        
        '<remarks/>
        Public m_strAto_ShojoJiyuCD As String
        
        '<remarks/>
        Public m_strAto_ShojoJiyu As String
        
        '<remarks/>
        Public m_strAto_ShojoTdkdYMD As String
        
        '<remarks/>
        Public m_strAto_ShojoTdkdTuciKB As String
        
        '<remarks/>
        Public m_strAto_TenshutsuYoteiIdoYMD As String
        
        '<remarks/>
        Public m_strAto_TenshutsuKktiIdoYMD As String
        
        '<remarks/>
        Public m_strAto_TenshutsuKktiTuciYMD As String
        
        '<remarks/>
        Public m_strAto_TestsuMiTdkIdoYMD As String
        
        '<remarks/>
        Public m_strAto_TestsuMiTdkTuciYMD As String
        
        '<remarks/>
        Public m_strAto_TenshutsunyuRiyuCD As String
        
        '<remarks/>
        Public m_strAto_TenshutsunyuRiyu As String
        
        '<remarks/>
        Public m_strAto_TenumaeJ_YubinNO As String
        
        '<remarks/>
        Public m_strAto_TenumaeJ_ZJushoCD As String
        
        '<remarks/>
        Public m_strAto_TenumaeJ_Jusho As String
        
        '<remarks/>
        Public m_strAto_TenumaeJ_Banchi As String
        
        '<remarks/>
        Public m_strAto_TenumaeJ_Katagaki As String
        
        '<remarks/>
        Public m_strAto_TenumaeJ_StaiNusmei As String
        
        '<remarks/>
        Public m_strAto_TenumaeJ_MiTdkFG As String
        
        '<remarks/>
        Public m_strAto_SaishuJ_YubinNO As String
        
        '<remarks/>
        Public m_strAto_SaishuJ_ZJushoCD As String
        
        '<remarks/>
        Public m_strAto_SaishuJ_NJushoCD As String
        
        '<remarks/>
        Public m_strAto_SaishuJ_Jusho As String
        
        '<remarks/>
        Public m_strAto_SaishuJ_Banchi As String
        
        '<remarks/>
        Public m_strAto_SaishuJ_Katagaki As String
        
        '<remarks/>
        Public m_strAto_SaishuJ_StaiNusmei As String
        
        '<remarks/>
        Public m_strAto_TenshutsuYoteiYubinNO As String
        
        '<remarks/>
        Public m_strAto_TenshutsuYoteiZJushoCD As String
        
        '<remarks/>
        Public m_strAto_TenshutsuYoteiJusho As String
        
        '<remarks/>
        Public m_strAto_TenshutsuYoteiBanchi As String
        
        '<remarks/>
        Public m_strAto_TenshutsuYoteiKatagaki As String
        
        '<remarks/>
        Public m_strAto_TenshutsuYoteiStaiNusmei As String
        
        '<remarks/>
        Public m_strAto_TenshutsuKktiYubinNO As String
        
        '<remarks/>
        Public m_strAto_TenshutsuKktiZJushoCD As String
        
        '<remarks/>
        Public m_strAto_TenshutsuKktiJusho As String
        
        '<remarks/>
        Public m_strAto_TenshutsuKktiBanchi As String
        
        '<remarks/>
        Public m_strAto_TenshutsuKktiKatagaki As String
        
        '<remarks/>
        Public m_strAto_TenshutsuKktiStaiNusmei As String
        
        '<remarks/>
        Public m_strAto_TestsuMiTdkYubinNO As String
        
        '<remarks/>
        Public m_strAto_TestsuMiTdkZJushoCD As String
        
        '<remarks/>
        Public m_strAto_TestsuMiTdkJusho As String
        
        '<remarks/>
        Public m_strAto_TestsuMiTdkBanchi As String
        
        '<remarks/>
        Public m_strAto_TestsuMiTdkKatagaki As String
        
        '<remarks/>
        Public m_strAto_TestsuMiTdkStaiNusmei As String
        
        '<remarks/>
        Public m_strAto_TenshutsuKktiMiTdkFG As String
        
        '<remarks/>
        Public m_strAto_BikoYMD As String
        
        '<remarks/>
        Public m_strAto_Biko As String
        
        '<remarks/>
        Public m_strAto_BikoFG As String
        
        '<remarks/>
        Public m_strAto_BikoTenshutsuKktiJushoFG As String
        
        '<remarks/>
        Public m_strAto_UtsushiKB As String
        
        '<remarks/>
        Public m_strAto_KaiseiatoFG As String
        
        '<remarks/>
        Public m_strAto_KaiseimaeFG As String
        
        '<remarks/>
        Public m_strAto_JuminhyoShichosonCD As String
        
        '<remarks/>
        Public m_strAto_GyoseikuCD As String
        
        '<remarks/>
        Public m_strAto_Gyoseikumei As String
        
        '<remarks/>
        Public m_strAto_ChikuCD1 As String
        
        '<remarks/>
        Public m_strAto_Chikumei1 As String
        
        '<remarks/>
        Public m_strAto_ChikuCD2 As String
        
        '<remarks/>
        Public m_strAto_Chikumei2 As String
        
        '<remarks/>
        Public m_strAto_ChikuCD3 As String
        
        '<remarks/>
        Public m_strAto_Chikumei3 As String
        
        '<remarks/>
        Public m_strAto_TohyokuCD As String
        
        '<remarks/>
        Public m_strAto_ShogakkokuCD As String
        
        '<remarks/>
        Public m_strAto_ChugakkokuCD As String
        
        '<remarks/>
        Public m_strAto_HogoshaJuminCD As String
        
        '<remarks/>
        Public m_strAto_KanjiHogoshamei As String
        
        '<remarks/>
        Public m_strAto_KanaHogoshamei As String
        
        '<remarks/>
        Public m_strAto_KikaYMD As String
        
        '<remarks/>
        Public m_strAto_KariIdoKB As String
        
        '<remarks/>
        Public m_strAto_ShoriTeishiKB As String
        
        '<remarks/>
        Public m_strAto_ShoriTeishiRiyu As String
        
        '<remarks/>
        Public m_strAto_ShoriYokushiKB As String
        
        '<remarks/>
        Public m_strAto_ShoriYokushiRiyu As String
        
        '<remarks/>
        Public m_strAto_HanyoCD As String
        
        '<remarks/>
        Public m_strAto_FRNmei As String
        
        '<remarks/>
        Public m_strAto_KanaFRNmei As String
        
        '<remarks/>
        Public m_strAto_Tsushomei As String
        
        '<remarks/>
        Public m_strAto_KanaTsushomei As String
        
        '<remarks/>
        Public m_strAto_KokusekiCD As String
        
        '<remarks/>
        Public m_strAto_Kokuseki As String
        
        '<remarks/>
        Public m_strAto_ZairyuSkakCD As String
        
        '<remarks/>
        Public m_strAto_ZairyuSkak As String
        
        '<remarks/>
        Public m_strAto_ZairyuKikan As String
        
        '<remarks/>
        Public m_strAto_Zairyu_ST_YMD As String
        
        '<remarks/>
        Public m_strAto_Zairyu_ED_YMD As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://Reams.ndensan.co.jp")>  _
    Public Class AAKOBETSUSENKYOParamClass
        
        '<remarks/>
        Public m_strJuminCD As String
        
        '<remarks/>
        Public m_strSenkyoShikakuKB As String
        
        '<remarks/>
        Public m_strTohyokuCD As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://Reams.ndensan.co.jp")>  _
    Public Class AAKOBETSUNENKINParamClass
        
        '<remarks/>
        Public m_strJUMINCD As String
        
        '<remarks/>
        Public m_strKSNENKNNO As String
        
        '<remarks/>
        Public m_strSKAKSHUTKYMD As String
        
        '<remarks/>
        Public m_strSKAKSHUTKSHU As String
        
        '<remarks/>
        Public m_strSKAKSHUTKRIYUCD As String
        
        '<remarks/>
        Public m_strSKAKSSHTSYMD As String
        
        '<remarks/>
        Public m_strSKAKSSHTSRIYUCD As String
        
        '<remarks/>
        Public m_strJKYNENKNKIGO1 As String
        
        '<remarks/>
        Public m_strJKYNENKNNO1 As String
        
        '<remarks/>
        Public m_strJKYNENKNSHU1 As String
        
        '<remarks/>
        Public m_strJKYNENKNEDABAN1 As String
        
        '<remarks/>
        Public m_strJKYNENKNKB1 As String
        
        '<remarks/>
        Public m_strJKYNENKNKIGO2 As String
        
        '<remarks/>
        Public m_strJKYNENKNNO2 As String
        
        '<remarks/>
        Public m_strJKYNENKNSHU2 As String
        
        '<remarks/>
        Public m_strJKYNENKNEDABAN2 As String
        
        '<remarks/>
        Public m_strJKYNENKNKB2 As String
        
        '<remarks/>
        Public m_strJKYNENKNKIGO3 As String
        
        '<remarks/>
        Public m_strJKYNENKNNO3 As String
        
        '<remarks/>
        Public m_strJKYNENKNSHU3 As String
        
        '<remarks/>
        Public m_strJKYNENKNEDABAN3 As String
        
        '<remarks/>
        Public m_strJKYNENKNKB3 As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://Reams.ndensan.co.jp")>  _
    Public Class AAKOBETSUKOKUHOParamClass
        
        '<remarks/>
        Public m_strJUMINCD As String
        
        '<remarks/>
        Public m_strKOKUHONO As String
        
        '<remarks/>
        Public m_strKOKUHOSHIKAKUKB As String
        
        '<remarks/>
        Public m_strKOKUHOSHIKAKUKBMEISHO As String
        
        '<remarks/>
        Public m_strKOKUHOSHIKAKUKBRYAKUSHO As String
        
        '<remarks/>
        Public m_strKOKUHOGAKUENKB As String
        
        '<remarks/>
        Public m_strKOKUHOGAKUENKBMEISHO As String
        
        '<remarks/>
        Public m_strKOKUHOGAKUENKBRYAKUSHO As String
        
        '<remarks/>
        Public m_strKOKUHOSHUTOKUYMD As String
        
        '<remarks/>
        Public m_strKOKUHOSOSHITSUYMD As String
        
        '<remarks/>
        Public m_strKOKUHOTISHKKB As String
        
        '<remarks/>
        Public m_strKOKUHOTISHKKBMEISHO As String
        
        '<remarks/>
        Public m_strKOKUHOTISHKKBRYAKUSHO As String
        
        '<remarks/>
        Public m_strKOKUHOTISHKHONHIKB As String
        
        '<remarks/>
        Public m_strKOKUHOTISHKHONHIKBMEISHO As String
        
        '<remarks/>
        Public m_strKOKUHOTISHKHONHIKBRYAKUSHO As String
        
        '<remarks/>
        Public m_strKOKUHOTISHKGAITOYMD As String
        
        '<remarks/>
        Public m_strKOKUHOTISHKHIGAITOYMD As String
        
        '<remarks/>
        Public m_strKOKUHOHOKENSHOKIGO As String
        
        '<remarks/>
        Public m_strKOKUHOHOKENSHONO As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://Reams.ndensan.co.jp")>  _
    Public Class AAKOBETSUKAIGOParamClass
        
        '<remarks/>
        Public m_strJUMINCD As String
        
        '<remarks/>
        Public m_strHIHKNSHANO As String
        
        '<remarks/>
        Public m_strSKAKSHUTKYMD As String
        
        '<remarks/>
        Public m_strSKAKSSHTSYMD As String
        
        '<remarks/>
        Public m_strSKAKHIHOKENSHAKB As String
        
        '<remarks/>
        Public m_strJUSHOCHITKRIKB As String
        
        '<remarks/>
        Public m_strJUKYUSHAKB As String
        
        '<remarks/>
        Public m_strYOKAIGJOTAIKBCD As String
        
        '<remarks/>
        Public m_strKAIGSKAKKB As String
        
        '<remarks/>
        Public m_strNINTEIKAISHIYMD As String
        
        '<remarks/>
        Public m_strNINTEISHURYOYMD As String
        
        '<remarks/>
        Public m_strJUKYUNINTEIYMD As String
        
        '<remarks/>
        Public m_strJUKYUNINTEITORIKESHIYMD As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://Reams.ndensan.co.jp")>  _
    Public Class AAKOBETSUJITEParamClass
        
        '<remarks/>
        Public m_strJUMINCD As String
        
        '<remarks/>
        Public m_strHIYOKB As String
        
        '<remarks/>
        Public m_strJIDOTEATESTYM As String
        
        '<remarks/>
        Public m_strJIDOTEATEEDYM As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://Reams.ndensan.co.jp")>  _
    Public Class AAKOBETSUINKANParamClass
        
        '<remarks/>
        Public m_strJUMINCD As String
        
        '<remarks/>
        Public m_strINKANNO As String
        
        '<remarks/>
        Public m_strINKANTOROKUKB As String
    End Class
End Namespace
